version: '3.3'

volumes:
  pg_data:
  static:
  media:
  frontend_static:  # Общий том для статических файлов
  docs:

services:
  foodgramdb:
    image: postgres:14.5
    env_file: .env
    volumes:
      - ${MEDIA_ROOT}/db:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_ON_DOCKER}
    depends_on:
      - foodgramdb
    volumes:
      - static:/backend_static
      - media:${MEDIA_ROOT}

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/  # Копируем в общий том
    volumes:
      - frontend_static:/frontend_static  # Монтируем общий том

  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
      - frontend_static:/usr/share/nginx/html/
      - media:${MEDIA_ROOT}
      - ./docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8000:80
