version: '3.3'

volumes:
  pg_data:
  static:
  media:
  docs:

services:
  foodgramdb:
    image: postgres:14.5
    env_file: .env
    volumes:
      - ./foodgram_db/:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend
    env_file: .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_ON_DOCKER}
    depends_on:
      - foodgramdb
    volumes:
      - media:${MEDIA_ROOT_SERVER}
      - static:/backend_static


  frontend:
    env_file: .env
    image: ${DOCKER_USERNAME}/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: ${DOCKER_USERNAME}/foodgram_gateway
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:${MEDIA_ROOT_SERVER}
      - ./docs/:/usr/share/nginx/html/api/docs/

