version: '3.3'

volumes:
  food_pg_data:
  food_static:
  food_media:
  food_docs:

services:
  foodgramdb:
    image: postgres:14.5
    env_file: .env
    volumes:
      - food_pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend
    env_file: .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_ON_DOCKER}
    depends_on:
      - foodgramdb
    volumes:
      - food_media:${MEDIA_ROOT_SERVER}
      - food_static:/backend_static

  frontend:
    env_file: .env
    image: ${DOCKER_USERNAME}/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - food_static:/static

  gateway:
    image: ${DOCKER_USERNAME}/foodgram_gateway
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - food_static:/static
      - food_media:${MEDIA_ROOT_SERVER}
      - food_docs:/usr/share/nginx/html/api/docs/

